[package]
name = "dora-v4l-capture"
version = "0.1.0"
edition = "2021"

[dependencies]
dora-node-api = { version = "0.3.10", features = ["tracing"] }
dora-image-utils = { path = "../image-utils" }
eyre = "0.6"
log = "0.4"
kornia = { path = "../../../crates/kornia", features = ["v4l", "arrow"] }
arrow = "55.2.0"
