[build]
default-target = "x86_64-unknown-linux-gnu"

[target.x86_64-unknown-linux-gnu]
dockerfile = "devel-x86_64.Dockerfile"

[target.aarch64-unknown-linux-gnu]
dockerfile = "devel-aarch64.Dockerfile"

[target.i686-unknown-linux-gnu]
dockerfile = "devel-i686.Dockerfile"
