[package]
name = "webcam_simple"
version = "0.1.0"
authors = ["Edgar Riba <edgar.riba@gmail.com>"]
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
ctrlc = "3.4.4"
kornia-rs = { workspace = true }
rerun = "0.16.0"
tokio = { version = "1" }
