[package]
name = "kornia_vlm_pyo3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "kornia_vlm_pyo3"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.25.0"

kornia-vlm = { path = "../../../../crates/kornia-vlm", features = ["cuda"] }
kornia-io = { path = "../../../../crates/kornia-io" }

[workspace] # exclude it from the general workspace
