"""Type stubs for the ``kornia_rs.image`` submodule (compiled extension)."""

from __future__ import annotations

from typing import Any, Optional, Sequence

import numpy as np

class ImageSize:
    def __init__(self, width: int, height: int) -> None: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...

class PixelFormat:
    U8: PixelFormat
    U16: PixelFormat
    F32: PixelFormat

class ImageLayout:
    def __init__(
        self, image_size: ImageSize, channels: int, pixel_format: PixelFormat
    ) -> None: ...
    @property
    def image_size(self) -> ImageSize: ...
    @property
    def channels(self) -> int: ...
    @property
    def pixel_format(self) -> PixelFormat: ...

class Image:
    """An owned image/tensor buffer backed by a numpy ``uint8``/``uint16``/``float32`` array."""

    def __init__(self, data: np.ndarray, mode: Optional[str] = ...) -> None: ...

    # --- constructors ---
    @staticmethod
    def frombuffer(data: Any, mode: Optional[str] = ...) -> Image: ...
    @staticmethod
    def fromarray(data: np.ndarray, mode: Optional[str] = ...) -> Image: ...
    @staticmethod
    def frombytes(
        data: bytes,
        width: int,
        height: int,
        channels: int = ...,
        mode: Optional[str] = ...,
        dtype: Optional[str] = ...,
    ) -> Image: ...
    @staticmethod
    def load(path: str) -> Image: ...
    @staticmethod
    def decode(data: bytes, mode: str = ...) -> Image: ...
    @staticmethod
    def open(fp: Any, mode: str = ...) -> Image: ...
    @staticmethod
    def new(mode: str, size: tuple[int, int], color: Any = ...) -> Image: ...

    # --- properties ---
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def channels(self) -> int: ...
    @property
    def mode(self) -> str: ...
    @property
    def format(self) -> Optional[str]: ...
    @property
    def size(self) -> tuple[int, int]: ...
    @property
    def shape(self) -> tuple[int, int, int]: ...
    @property
    def dtype(self) -> np.dtype: ...
    @property
    def data(self) -> np.ndarray: ...
    @property
    def nbytes(self) -> int: ...
    @property
    def data_ptr(self) -> int:
        """Host address (int) of the underlying contiguous buffer.

        Stable for the lifetime of this ``Image``; hand it (with ``shape`` /
        ``nbytes``) to cudarc / TensorRT for a host→device copy.
        """
        ...

    # --- IO ---
    def save(
        self,
        fp: Any,
        format: Optional[str] = ...,
        quality: int = ...,
        compress_level: Optional[int] = ...,
        subsampling: Optional[int] = ...,
    ) -> None: ...
    def encode(
        self,
        format: str,
        quality: int = ...,
        compress_level: Optional[int] = ...,
        subsampling: Optional[int] = ...,
    ) -> bytes: ...
    def tobytes(self) -> bytes: ...
    def to_numpy(self) -> np.ndarray:
        """Owned deep copy of the buffer as a numpy array."""
        ...
    def numpy(self) -> np.ndarray:
        """Zero-copy numpy view of the underlying buffer (shares memory)."""
        ...
    def copy(self) -> Image: ...

    # --- transforms ---
    def resize(self, width: int, height: int, interpolation: str = ...) -> Image: ...
    def resize_normalize_to_tensor(
        self,
        width: int,
        height: int,
        mean: Sequence[float],
        std: Sequence[float],
    ) -> Image:
        """Fused resize + per-channel normalize + HWC→CHW into an owned float32
        tensor ``Image`` (CHW), for any target size. NEON/AVX2-vectorized, single
        pass, copy-free. Use ``.numpy()`` for a view and ``.data_ptr`` for the
        host address to hand to cudarc / TensorRT. Output is ``(x/255 - mean)/std``.
        """
        ...
    def flip_horizontal(self) -> Image: ...
    def flip_vertical(self) -> Image: ...
    def crop(
        self,
        x: int | tuple[int, int, int, int],
        y: Optional[int] = ...,
        width: Optional[int] = ...,
        height: Optional[int] = ...,
    ) -> Image: ...
    def gaussian_blur(self, kernel_size: int = ..., sigma: float = ...) -> Image: ...
    def box_blur(self, kernel_size: int = ...) -> Image: ...
    def adjust_brightness(self, factor: float) -> Image: ...
    def adjust_contrast(self, factor: float) -> Image: ...
    def adjust_saturation(self, factor: float) -> Image: ...
    def adjust_hue(self, factor: float) -> Image: ...
    def normalize(
        self, mean: tuple[float, float, float], std: tuple[float, float, float]
    ) -> np.ndarray: ...
    def convert(self, mode: str) -> Image: ...
    def to_grayscale(self) -> Image: ...
    def to_rgb(self) -> Image: ...
    def colormap(self, colormap: str) -> Image: ...
    def rotate(self, angle: float) -> Image: ...

    # --- dunders ---
    def __array__(self, dtype: Any = ..., copy: Any = ...) -> np.ndarray: ...
    def __len__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __enter__(self) -> Image: ...
    def __exit__(self, *args: Any) -> None: ...
