"""Type stubs for the ``kornia_rs.imgproc`` submodule.

Color ops dispatch on residency: a numpy array (HWC) runs on the CPU and returns
a numpy array; a device ``Image`` runs the GPU kernel and returns a device
``Image``; a host ``Image`` runs on the CPU and returns a host ``Image``. u8 ops
return uint8, the f32 perceptual/cylindrical conversions return float32. Naming
is ``<out>_from_<in>``.
"""

from __future__ import annotations

from typing import Optional, Sequence, Union

import numpy as np

from .image import Image

# A color op accepts a numpy array or an ``Image`` and returns the same kind
# (numpy -> numpy, Image -> Image; device Images run on the GPU).
_Color = Union[np.ndarray, Image]

# --- channel / colorspace (u8) ---
def rgb_from_gray(image: _Color) -> _Color: ...
def gray_from_rgb(image: _Color) -> _Color: ...
def gray_from_rgb_f32(image: np.ndarray) -> np.ndarray: ...
def bgr_from_rgb(image: _Color) -> _Color: ...
def rgba_from_rgb(image: _Color) -> _Color: ...
def rgb_from_rgba(
    image: _Color, background: Optional[Sequence[int]] = ...
) -> _Color: ...
def rgb_from_bgra(
    image: _Color, background: Optional[Sequence[int]] = ...
) -> _Color: ...
def apply_colormap(image: _Color, colormap: str) -> _Color: ...

# --- f32 perceptual / cylindrical / matrix conversions (3->3) ---
# hsv/lab/ycbcr/sepia have GPU kernels; the rest are CPU-only (a device Image
# raises "no GPU kernel").
def hsv_from_rgb(image: _Color) -> _Color: ...
def rgb_from_hsv(image: _Color) -> _Color: ...
def hls_from_rgb(image: _Color) -> _Color: ...
def rgb_from_hls(image: _Color) -> _Color: ...
def xyz_from_rgb(image: _Color) -> _Color: ...
def rgb_from_xyz(image: _Color) -> _Color: ...
def lab_from_rgb(image: _Color) -> _Color: ...
def rgb_from_lab(image: _Color) -> _Color: ...
def luv_from_rgb(image: _Color) -> _Color: ...
def rgb_from_luv(image: _Color) -> _Color: ...
def linear_rgb_from_rgb(image: _Color) -> _Color: ...
def rgb_from_linear_rgb(image: _Color) -> _Color: ...
def ycbcr_from_rgb(image: _Color) -> _Color: ...
def rgb_from_ycbcr(image: _Color) -> _Color: ...
def yuv_from_rgb(image: _Color) -> _Color: ...
def rgb_from_yuv(image: _Color) -> _Color: ...
def sepia_from_rgb(image: _Color) -> _Color: ...

# --- Bayer demosaic (u8 mosaic -> RGB) ---
def rgb_from_bayer(image: _Color, pattern: str) -> _Color:
    """``pattern`` is the sensor layout: ``"rggb"`` / ``"bggr"`` / ``"grbg"`` / ``"gbrg"``."""
    ...

# --- packed/planar YUV video decode (1-D uint8 buffer -> (H, W, 3) RGB) ---
def rgb_from_yuyv(data: np.ndarray, width: int, height: int) -> np.ndarray: ...
def rgb_from_uyvy(data: np.ndarray, width: int, height: int) -> np.ndarray: ...
def rgb_from_yvyu(data: np.ndarray, width: int, height: int) -> np.ndarray: ...
def rgb_from_nv12(data: np.ndarray, width: int, height: int) -> np.ndarray: ...
def rgb_from_nv21(data: np.ndarray, width: int, height: int) -> np.ndarray: ...
def rgb_from_i420(data: np.ndarray, width: int, height: int) -> np.ndarray: ...
def rgb_from_yv12(data: np.ndarray, width: int, height: int) -> np.ndarray: ...

# --- reverse YUV encode (RGB -> packed/planar YUV, 1-D uint8 buffer) ---
def yuyv_from_rgb(image: np.ndarray) -> np.ndarray:
    """Encode (H,W,3) uint8 RGB to a packed 4:2:2 YUYV buffer (1-D, len W*H*2)."""
    ...
def nv12_from_rgb(image: np.ndarray) -> np.ndarray:
    """Encode (H,W,3) uint8 RGB to a planar 4:2:0 NV12 buffer (1-D, len W*H*3/2)."""
    ...

# --- geometric ---
def resize(
    image: np.ndarray | Image,
    new_size: tuple[int, int],
    interpolation: str,
    antialias: bool = ...,
    out: Image | None = ...,
) -> np.ndarray | Image:
    """``new_size`` is ``(height, width)``; ``interpolation`` is e.g. ``"bilinear"`` / ``"nearest"``.

    A device ``Image`` (f32 3-channel, or u8 1/3/4-channel) runs on the GPU,
    bit-identical to the matching CPU path, and returns a device ``Image``.
    ``antialias`` shapes the u8 bicubic/lanczos kernels (CPU and GPU alike)
    and is ignored for f32 and for nearest/bilinear."""
    ...
def warp_affine(
    image: np.ndarray | Image,
    m: Sequence[float],
    new_size: tuple[int, int],
    interpolation: str,
    out: Optional[np.ndarray] = ...,
) -> np.ndarray | Image:
    """``m`` is the 2x3 affine matrix (row-major, length 6).

    A device ``Image`` (f32, 3-channel) runs on the GPU and returns a device
    ``Image``; ``out=`` is unsupported there."""
    ...
def warp_perspective(
    image: np.ndarray | Image,
    m: Sequence[float],
    new_size: tuple[int, int],
    interpolation: str,
    out: Optional[np.ndarray] = ...,
) -> np.ndarray | Image:
    """``m`` is the 3x3 perspective matrix (row-major, length 9).

    A device ``Image`` (f32, 3-channel) runs on the GPU and returns a device
    ``Image``; ``out=`` is unsupported there."""
    ...
def crop(image: np.ndarray, x: int, y: int, width: int, height: int) -> np.ndarray: ...
def horizontal_flip(image: np.ndarray) -> np.ndarray: ...
def vertical_flip(image: np.ndarray) -> np.ndarray: ...

# --- filtering / enhance / stats ---
def gaussian_blur(
    image: np.ndarray, kernel_size: tuple[int, int], sigma: tuple[float, float]
) -> np.ndarray: ...
def box_blur(image: np.ndarray, kernel_size: tuple[int, int]) -> np.ndarray: ...
def dilate(
    image: np.ndarray | Image,
    kernel: str = ...,
    size: tuple[int, int] = ...,
    border: str = ...,
    constant_value: int = ...,
) -> np.ndarray | Image:
    """Neighborhood maximum over a ``"box"`` / ``"cross"`` / ``"ellipse"``
    structuring element of ``size`` ``(height, width)``. ``border`` is one of
    ``"constant"`` / ``"replicate"`` / ``"reflect101"`` / ``"reflect"`` /
    ``"wrap"``. A u8 device ``Image`` (1/3/4-channel) runs on the GPU,
    bit-identical to the numpy CPU path."""
    ...
def erode(
    image: np.ndarray | Image,
    kernel: str = ...,
    size: tuple[int, int] = ...,
    border: str = ...,
    constant_value: int = ...,
) -> np.ndarray | Image:
    """Neighborhood minimum — see :func:`dilate` for parameters and the GPU path."""
    ...
def adjust_brightness(image: np.ndarray, factor: float) -> np.ndarray: ...
def add_weighted(
    src1: np.ndarray, alpha: float, src2: np.ndarray, beta: float, gamma: float
) -> np.ndarray: ...
def normalize_mean_std(
    image: np.ndarray, mean: Sequence[float], std: Sequence[float]
) -> np.ndarray:
    """Per-channel ``(x/255 - mean) / std`` (3-channel u8 -> float32 HWC)."""
    ...
def compute_histogram(image: np.ndarray | Image, num_bins: int) -> list[int]: ...
def equalize_hist(image: np.ndarray | Image) -> np.ndarray | Image: ...
def clahe(
    image: np.ndarray | Image,
    clip_limit: float = 40.0,
    grid_size: tuple[int, int] = (8, 8),
) -> np.ndarray | Image: ...
