"""Type stubs for the ``kornia_rs.imgproc`` submodule.

All ops take/return C-contiguous numpy arrays (HWC). u8 ops return uint8, the
f32 perceptual/cylindrical conversions return float32. Naming is ``<out>_from_<in>``.
"""

from __future__ import annotations

from typing import Optional, Sequence

import numpy as np

# --- channel / colorspace (u8) ---
def rgb_from_gray(image: np.ndarray) -> np.ndarray: ...
def gray_from_rgb(image: np.ndarray) -> np.ndarray: ...
def gray_from_rgb_f32(image: np.ndarray) -> np.ndarray: ...
def bgr_from_rgb(image: np.ndarray) -> np.ndarray: ...
def rgb_from_rgba(
    image: np.ndarray, background: Optional[Sequence[int]] = ...
) -> np.ndarray: ...
def rgb_from_bgra(
    image: np.ndarray, background: Optional[Sequence[int]] = ...
) -> np.ndarray: ...
def apply_colormap(image: np.ndarray, colormap: str) -> np.ndarray: ...

# --- f32 perceptual / cylindrical / matrix conversions (3->3) ---
def hsv_from_rgb(image: np.ndarray) -> np.ndarray: ...
def rgb_from_hsv(image: np.ndarray) -> np.ndarray: ...
def hls_from_rgb(image: np.ndarray) -> np.ndarray: ...
def rgb_from_hls(image: np.ndarray) -> np.ndarray: ...
def xyz_from_rgb(image: np.ndarray) -> np.ndarray: ...
def rgb_from_xyz(image: np.ndarray) -> np.ndarray: ...
def lab_from_rgb(image: np.ndarray) -> np.ndarray: ...
def rgb_from_lab(image: np.ndarray) -> np.ndarray: ...
def luv_from_rgb(image: np.ndarray) -> np.ndarray: ...
def rgb_from_luv(image: np.ndarray) -> np.ndarray: ...
def linear_rgb_from_rgb(image: np.ndarray) -> np.ndarray: ...
def rgb_from_linear_rgb(image: np.ndarray) -> np.ndarray: ...
def ycbcr_from_rgb(image: np.ndarray) -> np.ndarray: ...
def rgb_from_ycbcr(image: np.ndarray) -> np.ndarray: ...
def yuv_from_rgb(image: np.ndarray) -> np.ndarray: ...
def rgb_from_yuv(image: np.ndarray) -> np.ndarray: ...
def sepia_from_rgb(image: np.ndarray) -> np.ndarray: ...

# --- Bayer demosaic (u8 mosaic -> RGB) ---
def rgb_from_bayer(image: np.ndarray, pattern: str) -> np.ndarray:
    """``pattern`` is the sensor layout: ``"rggb"`` / ``"bggr"`` / ``"grbg"`` / ``"gbrg"``."""
    ...

# --- packed/planar YUV video decode (1-D uint8 buffer -> (H, W, 3) RGB) ---
def rgb_from_yuyv(data: np.ndarray, width: int, height: int) -> np.ndarray: ...
def rgb_from_uyvy(data: np.ndarray, width: int, height: int) -> np.ndarray: ...
def rgb_from_yvyu(data: np.ndarray, width: int, height: int) -> np.ndarray: ...
def rgb_from_nv12(data: np.ndarray, width: int, height: int) -> np.ndarray: ...
def rgb_from_nv21(data: np.ndarray, width: int, height: int) -> np.ndarray: ...
def rgb_from_i420(data: np.ndarray, width: int, height: int) -> np.ndarray: ...
def rgb_from_yv12(data: np.ndarray, width: int, height: int) -> np.ndarray: ...

# --- reverse YUV encode (RGB -> packed/planar YUV, 1-D uint8 buffer) ---
def yuyv_from_rgb(image: np.ndarray) -> np.ndarray:
    """Encode (H,W,3) uint8 RGB to a packed 4:2:2 YUYV buffer (1-D, len W*H*2)."""
    ...
def nv12_from_rgb(image: np.ndarray) -> np.ndarray:
    """Encode (H,W,3) uint8 RGB to a planar 4:2:0 NV12 buffer (1-D, len W*H*3/2)."""
    ...

# --- geometric ---
def resize(
    image: np.ndarray,
    new_size: tuple[int, int],
    interpolation: str,
    antialias: bool = ...,
) -> np.ndarray:
    """``new_size`` is ``(height, width)``; ``interpolation`` is e.g. ``"bilinear"`` / ``"nearest"``."""
    ...
def warp_affine(
    image: np.ndarray,
    m: Sequence[float],
    new_size: tuple[int, int],
    interpolation: str,
    out: Optional[np.ndarray] = ...,
) -> np.ndarray:
    """``m`` is the 2x3 affine matrix (row-major, length 6)."""
    ...
def warp_perspective(
    image: np.ndarray,
    m: Sequence[float],
    new_size: tuple[int, int],
    interpolation: str,
    out: Optional[np.ndarray] = ...,
) -> np.ndarray:
    """``m`` is the 3x3 perspective matrix (row-major, length 9)."""
    ...
def crop(image: np.ndarray, x: int, y: int, width: int, height: int) -> np.ndarray: ...
def horizontal_flip(image: np.ndarray) -> np.ndarray: ...
def vertical_flip(image: np.ndarray) -> np.ndarray: ...

# --- filtering / enhance / stats ---
def gaussian_blur(
    image: np.ndarray, kernel_size: tuple[int, int], sigma: tuple[float, float]
) -> np.ndarray: ...
def box_blur(image: np.ndarray, kernel_size: tuple[int, int]) -> np.ndarray: ...
def adjust_brightness(image: np.ndarray, factor: float) -> np.ndarray: ...
def add_weighted(
    src1: np.ndarray, alpha: float, src2: np.ndarray, beta: float, gamma: float
) -> np.ndarray: ...
def normalize_mean_std(
    image: np.ndarray, mean: Sequence[float], std: Sequence[float]
) -> np.ndarray:
    """Per-channel ``(x/255 - mean) / std`` (3-channel u8 -> float32 HWC)."""
    ...
def compute_histogram(image: np.ndarray, num_bins: int) -> list[int]: ...
