#!/usr/bin/env python3
"""Regenerate kornia-xfeat parity fixtures from upstream XFeat PyTorch.

Run once, commit the output, do not re-run on a whim. See ../README.md.

Flow:
  1. Clone upstream XFeat at pinned commit (or use an existing clone).
  2. Load the published `xfeat.pt` checkpoint.
  3. Run the model on `input.png`, capturing the dense maps and sparse outputs.
  4. Dump everything to `<output>/` in the formats the Rust tests expect.
  5. Write `MANIFEST.toml` with the pinned commit hash + tolerances.
"""

import argparse
import hashlib
import json
import shutil
import subprocess
import sys
from pathlib import Path

UPSTREAM_REPO = "https://github.com/verlab/accelerated_features.git"
PINNED_COMMIT = "<TBD>"  # filled in on the first real run

MANIFEST_TEMPLATE = """\
# Auto-generated by tools/xfeat-regen-fixtures/regen.py.
format_version = 1

[upstream]
repo = "{repo}"
commit = "{commit}"
weights_file = "weights/xfeat.pt"
weights_sha256 = "{weights_sha}"

[input]
file = "input.png"
height = {h}
width = {w}
channels = 1

[tolerances.dense]
keypoint_logits_abs = 1e-3
keypoint_logits_rel = 1e-3
descriptor_pre_l2norm_abs = 5e-4
descriptor_pre_l2norm_rel = 1e-3
descriptor_post_l2norm_abs = 1e-4
descriptor_post_l2norm_rel = 1e-4
reliability_abs = 1e-4
reliability_rel = 1e-4

[tolerances.sparse]
keypoint_iou_min = 0.95
descriptor_cosdist_max = 1e-3
score_rel_max = 1e-2
count_abs_max = 1
"""


def sha256_of(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def clone_upstream(into: Path, commit: str) -> None:
    if into.exists():
        return
    subprocess.check_call(["git", "clone", UPSTREAM_REPO, str(into)])
    subprocess.check_call(["git", "-C", str(into), "checkout", commit])


def regen_one_image(xfeat, img_path: Path, out_dir: Path, top_k: int = 4096) -> tuple:
    """Run XFeat on one image and write per-image fixture files.

    Returns (h_a, w_a) — the processed resolution.
    """
    import torch
    import numpy as np
    from PIL import Image
    from safetensors.torch import save_file

    img = Image.open(img_path).convert("L")
    img_np = np.array(img, dtype=np.uint8)
    h_orig, w_orig = img_np.shape
    h_a = (h_orig // 32) * 32
    w_a = (w_orig // 32) * 32
    print(f"[regen] {img_path.name}: ({h_orig},{w_orig}) → ({h_a},{w_a})")

    dev = xfeat.dev
    with torch.no_grad():
        x = torch.from_numpy(img_np).float().unsqueeze(0).unsqueeze(0) / 255.0
        x_resized = torch.nn.functional.interpolate(
            x, size=(h_a, w_a), mode="bilinear", align_corners=False
        ).to(dev)

        save_file({"input_gray": x_resized.cpu().contiguous()},
                  str(out_dir / "input_preprocessed.safetensors"))

        feats, k1, h1 = xfeat.net(x_resized)
        kp_heatmap = xfeat.get_kpts_heatmap(k1)
        descriptors_post_l2 = torch.nn.functional.normalize(feats, dim=1)

        save_file(
            {
                "keypoint_logits": k1.cpu().contiguous(),
                "descriptor_pre_l2norm": feats.cpu().contiguous(),
                "descriptor_post_l2norm": descriptors_post_l2.cpu().contiguous(),
                "reliability": h1.cpu().contiguous(),
                "kp_heatmap_fullres": kp_heatmap.cpu().contiguous(),
            },
            str(out_dir / "expected_dense.safetensors"),
        )

        out = xfeat.detectAndCompute(x_resized, top_k=top_k)[0]
        sparse = {
            "keypoints": out["keypoints"].cpu().numpy().tolist(),
            "scores": out["scores"].cpu().numpy().tolist(),
            "descriptors": out["descriptors"].cpu().numpy().tolist(),
        }
        with (out_dir / "expected_sparse.json").open("w") as fh:
            json.dump(sparse, fh)

    return h_a, w_a


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--output", type=Path, required=True)
    ap.add_argument("--upstream", type=Path, default=Path("/tmp/accelerated_features"))
    ap.add_argument("--commit", default=PINNED_COMMIT)
    ap.add_argument("--images", nargs="+", default=["ref", "tgt"],
                    help="Image stems to process from upstream/assets/ (default: ref tgt)")
    args = ap.parse_args()

    if args.commit == "<TBD>":
        print("ERROR: PINNED_COMMIT not set. Pass --commit explicitly for the first regen.",
              file=sys.stderr)
        return 2

    args.output.mkdir(parents=True, exist_ok=True)
    clone_upstream(args.upstream, args.commit)

    sys.path.insert(0, str(args.upstream))
    import torch
    from modules.xfeat import XFeat  # type: ignore

    weights_path = args.upstream / "weights" / "xfeat.pt"
    weights_sha = sha256_of(weights_path)
    xfeat = XFeat(weights=str(weights_path))
    # Force CPU so fixtures are comparable to the Rust CPU implementation.
    xfeat = xfeat.cpu()
    xfeat.dev = torch.device("cpu")
    getattr(xfeat, "eval")()

    image_meta: list = []
    for stem in args.images:
        src = args.upstream / "assets" / f"{stem}.png"
        if not src.exists():
            print(f"[regen] warning: {src} not found, skipping", file=sys.stderr)
            continue
        img_dir = args.output / stem
        img_dir.mkdir(parents=True, exist_ok=True)
        dst = img_dir / "input.png"
        if not dst.exists():
            shutil.copy(src, dst)
        h_a, w_a = regen_one_image(xfeat, dst, img_dir)
        image_meta.append({"stem": stem, "height": h_a, "width": w_a})

    # Shared MANIFEST.toml at the top-level output directory.
    images_toml = "\n".join(
        f'[[images]]\nname = "{m["stem"]}"\nheight = {m["height"]}\nwidth = {m["width"]}\n'
        for m in image_meta
    )
    manifest = (
        MANIFEST_TEMPLATE.format(
            repo=UPSTREAM_REPO.removesuffix(".git"),
            commit=args.commit,
            weights_sha=weights_sha,
            h=image_meta[0]["height"] if image_meta else 0,
            w=image_meta[0]["width"] if image_meta else 0,
        )
        + "\n"
        + images_toml
    )
    (args.output / "MANIFEST.toml").write_text(manifest)
    print(f"[regen] wrote fixtures to {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
