//! OpenCV-compatible resize — byte-exact with `cv2.resize`.
//!
//! Opt-in compatibility mode reproducing OpenCV 4.x `INTER_LINEAR` and
//! `INTER_NEAREST` output exactly, for migration and cross-validation against
//! OpenCV pipelines. The default kornia resize ([`resize_native`] and the
//! `resize_fast_*` family) is *not* byte-compatible with OpenCV by design:
//! OpenCV quantizes u8 interpolation weights to 11-bit fixed point and
//! evaluates separably, both of which discard precision that kornia's own
//! paths keep.
//!
//! Every arithmetic step below mirrors `modules/imgproc/src/resize.cpp`
//! (OpenCV 4.x) — data types, expression grouping, and rounding included.
//! Deviating from any of it breaks byte-exactness, which the fixture tests in
//! `tests/opencv_compat.rs` (generated by `cv2` itself on this repository's
//! reference device) will catch.
//!
//! # What is reproduced
//!
//! * **u8 `INTER_LINEAR`** — bit-exact on any OpenCV build: the u8 path is
//!   11-bit fixed point (`INTER_RESIZE_COEF_SCALE = 2048`) and OpenCV's SIMD
//!   variants compute the identical integer sequence as its scalar code.
//! * **f32 `INTER_LINEAR`** — implements OpenCV's scalar reference semantics
//!   (separable float H-then-V from `resize.cpp`). Byte-identity for f32 is
//!   NOT well-defined across cv2 builds: vendor HALs replace this path (the
//!   aarch64 wheels route through Carotene/KleidiCV, whose NEON evaluation
//!   differs from OpenCV's own scalar reference by up to 3 ulp on ~18% of
//!   elements — measured against cv2 4.13 on Jetson Orin), and x86 wheels
//!   differ again. The fixture tests therefore assert a ≤4-ulp bound for f32
//!   and exact bytes for everything else.
//! * **`INTER_NEAREST`** — OpenCV's floor-based semantics
//!   (`sx = floor(x * src/dst)`), which is *not* pixel-center rounding; the
//!   half-pixel variant is OpenCV's separate `INTER_NEAREST_EXACT`, not
//!   reproduced here.
//!
//! [`resize_native`]: crate::resize::resize_native

use crate::interpolation::InterpolationMode;
use kornia_image::{Image, ImageError};

/// OpenCV `INTER_RESIZE_COEF_BITS`: u8 weights are quantized to this scale.
const COEF_BITS: i32 = 11;
const COEF_SCALE: f32 = (1 << COEF_BITS) as f32; // 2048.0

/// Per-axis linear-interpolation table: source offset of the left/top tap and
/// the two weights, exactly as OpenCV derives them.
struct LinearAxis {
    /// Left/top source index per destination index (element units, unclamped
    /// second tap is `ofs + 1` unless `border`).
    ofs: Vec<usize>,
    /// True where OpenCV routes the column through its single-tap border
    /// branch (weight `ONE` on `ofs`, no second tap).
    border: Vec<bool>,
    /// f32 weights `(1-f, f)` — used directly by the f32 path.
    wf: Vec<(f32, f32)>,
    /// i16 fixed-point weights `round_ties_even(w * 2048)` — the u8 path.
    wi: Vec<(i32, i32)>,
}

/// Mirror of the coefficient loop in `cv::hal::resize` for `INTER_LINEAR`.
///
/// The rounding chain is deliberately precise: `inv_scale = dst/src` in f64,
/// `scale = 1.0 / inv_scale` (two roundings — NOT `src/dst` directly), the
/// pixel-center expression evaluated in f64 then truncated to f32, and the
/// fraction reduced in f32. `cvRound` is round-half-to-even.
fn linear_axis(src_len: usize, dst_len: usize) -> LinearAxis {
    let inv_scale = dst_len as f64 / src_len as f64;
    let scale = 1.0 / inv_scale;

    let mut ofs = Vec::with_capacity(dst_len);
    let mut border = Vec::with_capacity(dst_len);
    let mut wf = Vec::with_capacity(dst_len);
    let mut wi = Vec::with_capacity(dst_len);

    for dx in 0..dst_len {
        let mut fx = ((dx as f64 + 0.5) * scale - 0.5) as f32;
        let mut sx = fx.floor() as isize;
        fx -= sx as f32;

        let mut is_border = false;
        if sx < 0 {
            sx = 0;
            fx = 0.0;
        }
        // OpenCV lowers `xmax` for sx >= src-1 and serves those columns from
        // the single-tap border branch (`D[dx] = S[xofs[dx]] * ONE`).
        if sx as usize >= src_len - 1 {
            sx = src_len as isize - 1;
            fx = 0.0;
            is_border = true;
        }

        ofs.push(sx as usize);
        border.push(is_border);
        wf.push((1.0 - fx, fx));
        wi.push((
            ((1.0 - fx) * COEF_SCALE).round_ties_even() as i32,
            (fx * COEF_SCALE).round_ties_even() as i32,
        ));
    }

    LinearAxis {
        ofs,
        border,
        wf,
        wi,
    }
}

/// `resizeNN`'s index table: `min(floor(i * src/dst), src-1)`, f64 math.
fn nearest_axis(src_len: usize, dst_len: usize) -> Vec<usize> {
    let inv_scale = dst_len as f64 / src_len as f64;
    let iscale = 1.0 / inv_scale;
    (0..dst_len)
        .map(|i| ((i as f64 * iscale).floor() as usize).min(src_len - 1))
        .collect()
}

fn check_sizes<T, const C: usize>(src: &Image<T, C>, dst: &Image<T, C>) -> Result<(), ImageError> {
    if src.cols() == 0 || src.rows() == 0 || dst.cols() == 0 || dst.rows() == 0 {
        return Err(ImageError::InvalidImageSize(
            src.cols(),
            src.rows(),
            dst.cols(),
            dst.rows(),
        ));
    }
    Ok(())
}

/// Resize a u8 image with byte-exact OpenCV `cv2.resize` semantics.
///
/// Supported modes: [`InterpolationMode::Bilinear`] (OpenCV `INTER_LINEAR`,
/// 11-bit fixed point — bit-exact on any OpenCV build) and
/// [`InterpolationMode::Nearest`] (OpenCV `INTER_NEAREST`, floor semantics).
///
/// This is the compatibility path; for kornia's own higher-precision resize
/// use [`resize_fast_u8`](crate::resize::resize_fast_u8).
///
/// # Errors
///
/// Returns an error for zero-sized images or an unsupported interpolation
/// mode.
pub fn resize_opencv_u8<const C: usize>(
    src: &Image<u8, C>,
    dst: &mut Image<u8, C>,
    interpolation: InterpolationMode,
) -> Result<(), ImageError> {
    check_sizes(src, dst)?;
    match interpolation {
        InterpolationMode::Nearest => resize_nearest(src, dst),
        InterpolationMode::Bilinear => resize_linear_u8(src, dst),
        mode => Err(ImageError::UnsupportedInterpolation(mode)),
    }
}

/// Resize an f32 image with OpenCV `cv2.resize` `INTER_LINEAR` /
/// `INTER_NEAREST` semantics (separable float evaluation, scalar reference
/// path).
///
/// # Errors
///
/// Returns an error for zero-sized images or an unsupported interpolation
/// mode.
pub fn resize_opencv_f32<const C: usize>(
    src: &Image<f32, C>,
    dst: &mut Image<f32, C>,
    interpolation: InterpolationMode,
) -> Result<(), ImageError> {
    check_sizes(src, dst)?;
    match interpolation {
        InterpolationMode::Nearest => resize_nearest(src, dst),
        InterpolationMode::Bilinear => resize_linear_f32(src, dst),
        mode => Err(ImageError::UnsupportedInterpolation(mode)),
    }
}

/// `resizeNN`: whole-pixel copies through the floor-based index tables.
fn resize_nearest<T: Copy, const C: usize>(
    src: &Image<T, C>,
    dst: &mut Image<T, C>,
) -> Result<(), ImageError> {
    let xs = nearest_axis(src.cols(), dst.cols());
    let ys = nearest_axis(src.rows(), dst.rows());
    let (src_w, dst_w) = (src.cols(), dst.cols());
    let s = src.as_slice();

    for (dy, row) in dst.as_slice_mut().chunks_exact_mut(dst_w * C).enumerate() {
        let srow = &s[ys[dy] * src_w * C..];
        for (dx, px) in row.chunks_exact_mut(C).enumerate() {
            px.copy_from_slice(&srow[xs[dx] * C..xs[dx] * C + C]);
        }
    }
    Ok(())
}

/// u8 `INTER_LINEAR`: horizontal pass into an i32 row buffer at scale 2^11,
/// vertical pass with OpenCV's split-shift fixed-point reduction.
fn resize_linear_u8<const C: usize>(
    src: &Image<u8, C>,
    dst: &mut Image<u8, C>,
) -> Result<(), ImageError> {
    let ax = linear_axis(src.cols(), dst.cols());
    let ay = linear_axis(src.rows(), dst.rows());
    let (src_w, src_h, dst_w) = (src.cols(), src.rows(), dst.cols());
    let s = src.as_slice();

    // H-resize one source row into an i32 buffer (values scaled by 2^11).
    let hresize = |sy: usize, out: &mut [i32]| {
        let srow = &s[sy * src_w * C..(sy + 1) * src_w * C];
        for dx in 0..dst_w {
            let sx = ax.ofs[dx] * C;
            if ax.border[dx] {
                // Border branch: single tap at weight ONE (2048).
                for k in 0..C {
                    out[dx * C + k] = (srow[sx + k] as i32) << COEF_BITS;
                }
            } else {
                let (a0, a1) = ax.wi[dx];
                for k in 0..C {
                    out[dx * C + k] = srow[sx + k] as i32 * a0 + srow[sx + C + k] as i32 * a1;
                }
            }
        }
    };

    // Two-row cache: dy advances monotonically, so the H-resized rows for
    // consecutive dst rows overlap and each source row is resized once.
    let mut rows: [(usize, Vec<i32>); 2] = [
        (usize::MAX, vec![0; dst_w * C]),
        (usize::MAX, vec![0; dst_w * C]),
    ];
    let get_row = |sy: usize, rows: &mut [(usize, Vec<i32>); 2], slot: usize| {
        if rows[0].0 == sy {
            rows.swap(0, slot);
        } else if rows[1].0 == sy {
            rows.swap(1, slot);
        } else {
            hresize(sy, &mut rows[slot].1);
            rows[slot].0 = sy;
        }
    };

    for (dy, drow) in dst.as_slice_mut().chunks_exact_mut(dst_w * C).enumerate() {
        let sy0 = ay.ofs[dy];
        let sy1 = (sy0 + 1).min(src_h - 1);
        let (b0, b1) = ay.wi[dy];
        // OpenCV's y-axis border columns fold into (b0, b1) = (2048, 0) with
        // sy1 clamped, which the arithmetic below already handles.

        get_row(sy0, &mut rows, 0);
        if sy1 != sy0 {
            get_row(sy1, &mut rows, 1);
        } else {
            let (head, tail) = rows.split_at_mut(1);
            tail[0].1.copy_from_slice(&head[0].1);
            tail[0].0 = sy1;
        }

        // OpenCV's u8 VResizeLinear specialization — the split-shift form, not
        // the generic (val + 2^21) >> 22 cast. The two are NOT bit-equivalent;
        // reproduce the split-shift exactly.
        for (d, (s0, s1)) in drow.iter_mut().zip(rows[0].1.iter().zip(&rows[1].1)) {
            *d = ((((b0 * (s0 >> 4)) >> 16) + ((b1 * (s1 >> 4)) >> 16) + 2) >> 2) as u8;
        }
    }
    Ok(())
}

/// f32 `INTER_LINEAR`: separable float evaluation, mirroring the scalar
/// `HResizeLinear<float,...>` / `VResizeLinear<float,...>` templates.
fn resize_linear_f32<const C: usize>(
    src: &Image<f32, C>,
    dst: &mut Image<f32, C>,
) -> Result<(), ImageError> {
    let ax = linear_axis(src.cols(), dst.cols());
    let ay = linear_axis(src.rows(), dst.rows());
    let (src_w, src_h, dst_w) = (src.cols(), src.rows(), dst.cols());
    let s = src.as_slice();

    let hresize = |sy: usize, out: &mut [f32]| {
        let srow = &s[sy * src_w * C..(sy + 1) * src_w * C];
        for dx in 0..dst_w {
            let sx = ax.ofs[dx] * C;
            if ax.border[dx] {
                // ONE == 1 for float: the border tap passes through.
                out[dx * C..dx * C + C].copy_from_slice(&srow[sx..sx + C]);
            } else {
                let (a0, a1) = ax.wf[dx];
                for k in 0..C {
                    out[dx * C + k] = srow[sx + k] * a0 + srow[sx + C + k] * a1;
                }
            }
        }
    };

    let mut rows: [(usize, Vec<f32>); 2] = [
        (usize::MAX, vec![0.0; dst_w * C]),
        (usize::MAX, vec![0.0; dst_w * C]),
    ];
    let get_row = |sy: usize, rows: &mut [(usize, Vec<f32>); 2], slot: usize| {
        if rows[0].0 == sy {
            rows.swap(0, slot);
        } else if rows[1].0 == sy {
            rows.swap(1, slot);
        } else {
            hresize(sy, &mut rows[slot].1);
            rows[slot].0 = sy;
        }
    };

    for (dy, drow) in dst.as_slice_mut().chunks_exact_mut(dst_w * C).enumerate() {
        let sy0 = ay.ofs[dy];
        let sy1 = (sy0 + 1).min(src_h - 1);
        let (b0, b1) = ay.wf[dy];

        get_row(sy0, &mut rows, 0);
        if sy1 != sy0 {
            get_row(sy1, &mut rows, 1);
        } else {
            let (head, tail) = rows.split_at_mut(1);
            tail[0].1.copy_from_slice(&head[0].1);
            tail[0].0 = sy1;
        }

        for (d, (s0, s1)) in drow.iter_mut().zip(rows[0].1.iter().zip(&rows[1].1)) {
            *d = s0 * b0 + s1 * b1;
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use kornia_image::ImageSize;

    /// Pins our reference arithmetic byte-for-byte on a hand-computed case, so
    /// the tolerance corridor in the cv2 fixture test cannot mask a regression
    /// in our own code.
    ///
    /// 4→2 halving: fx(dst 0) = (0.5)*2 - 0.5 = 0.5, fx(dst 1) = 2.5 — floor 2,
    /// frac 0.5, taps (2,3). Weights (1024, 1024) exactly. For src row
    /// [0, 100, 200, 255]: h(dst0) = 0*1024 + 100*1024 = 102400,
    /// h(dst1) = 200*1024 + 255*1024 = 465920. Vertical with equal rows
    /// (b = (1024,1024)), split-shift form:
    /// 102400>>4 = 6400; (1024*6400)>>16 = 100; (100+100+2)>>2 = 50 — the
    /// true 50.0. 465920>>4 = 29120; (1024*29120)>>16 = 455;
    /// (455+455+2)>>2 = 228 — the true 227.5 rounded up by the +2 bias.
    #[test]
    fn u8_linear_halving_matches_hand_computed_fixed_point() {
        let src = Image::<u8, 1>::new(
            ImageSize {
                width: 4,
                height: 2,
            },
            vec![0, 100, 200, 255, 0, 100, 200, 255],
        )
        .unwrap();
        let mut dst = Image::<u8, 1>::from_size_val(
            ImageSize {
                width: 2,
                height: 1,
            },
            0,
        )
        .unwrap();
        resize_opencv_u8(&src, &mut dst, InterpolationMode::Bilinear).unwrap();
        assert_eq!(dst.as_slice(), &[50, 228]);
    }

    /// OpenCV INTER_NEAREST is floor-based, not pixel-center: 4→2 picks source
    /// columns 0 and 2 (floor(x * 2)), not the rounded centers.
    #[test]
    fn nearest_uses_floor_semantics() {
        let src = Image::<u8, 1>::new(
            ImageSize {
                width: 4,
                height: 1,
            },
            vec![10, 20, 30, 40],
        )
        .unwrap();
        let mut dst = Image::<u8, 1>::from_size_val(
            ImageSize {
                width: 2,
                height: 1,
            },
            0,
        )
        .unwrap();
        resize_opencv_u8(&src, &mut dst, InterpolationMode::Nearest).unwrap();
        assert_eq!(dst.as_slice(), &[10, 30]);
    }

    /// Left/right border columns take the single-tap branch: upscaling 2→4,
    /// dst 0 maps to fx = -0.25 → clamped (sx=0, fx=0) and dst 3 maps past the
    /// last column → border branch. Both must pass the edge value through
    /// unchanged (weight ONE), for u8 and f32 alike.
    #[test]
    fn border_columns_pass_through() {
        let src = Image::<f32, 1>::new(
            ImageSize {
                width: 2,
                height: 1,
            },
            vec![0.125, 0.875],
        )
        .unwrap();
        let mut dst = Image::<f32, 1>::from_size_val(
            ImageSize {
                width: 4,
                height: 1,
            },
            0.0,
        )
        .unwrap();
        resize_opencv_f32(&src, &mut dst, InterpolationMode::Bilinear).unwrap();
        let out = dst.as_slice();
        assert_eq!(out[0], 0.125, "left border must be a pass-through");
        assert_eq!(out[3], 0.875, "right border must be a pass-through");
        // Interior: fx(1) = 0.25, fx(2) = 0.75 against taps (0.125, 0.875).
        assert_eq!(out[1], 0.125 * 0.75 + 0.875 * 0.25);
        assert_eq!(out[2], 0.125 * 0.25 + 0.875 * 0.75);
    }

    #[test]
    fn rejects_unsupported_modes_and_zero_sizes() {
        let src = Image::<u8, 1>::new(
            ImageSize {
                width: 2,
                height: 2,
            },
            vec![0; 4],
        )
        .unwrap();
        let mut dst = Image::<u8, 1>::from_size_val(
            ImageSize {
                width: 2,
                height: 2,
            },
            0,
        )
        .unwrap();
        assert!(resize_opencv_u8(&src, &mut dst, InterpolationMode::Bicubic).is_err());
    }
}
