[package]
name = "kornia-v4l-capture"
version = "0.1.0"
edition = "2021"

[dependencies]
dora-node-api = { version = "0.3.12", features = ["tracing"] }
kornia-io = { path = "../../../crates/kornia-io", features = ["v4l"] }

