"""Generate Rust LUT tables from cv2 colormap data.

Run: python scripts/gen_colormap_luts.py > crates/kornia-imgproc/src/color/colormap_luts.rs
Requires: pip install opencv-python numpy
"""
import cv2
import numpy as np
import sys

COLORMAPS = [
    ("AUTUMN",    cv2.COLORMAP_AUTUMN),
    ("BONE",      cv2.COLORMAP_BONE),
    ("JET",       cv2.COLORMAP_JET),
    ("WINTER",    cv2.COLORMAP_WINTER),
    ("RAINBOW",   cv2.COLORMAP_RAINBOW),
    ("OCEAN",     cv2.COLORMAP_OCEAN),
    ("SUMMER",    cv2.COLORMAP_SUMMER),
    ("SPRING",    cv2.COLORMAP_SPRING),
    ("COOL",      cv2.COLORMAP_COOL),
    ("HSV",       cv2.COLORMAP_HSV),
    ("PINK",      cv2.COLORMAP_PINK),
    ("HOT",       cv2.COLORMAP_HOT),
    ("PARULA",    cv2.COLORMAP_PARULA),
    ("MAGMA",     cv2.COLORMAP_MAGMA),
    ("INFERNO",   cv2.COLORMAP_INFERNO),
    ("PLASMA",    cv2.COLORMAP_PLASMA),
    ("VIRIDIS",   cv2.COLORMAP_VIRIDIS),
    ("CIVIDIS",   cv2.COLORMAP_CIVIDIS),
    ("TWILIGHT",  cv2.COLORMAP_TWILIGHT),
    ("TURBO",     cv2.COLORMAP_TURBO),
    ("DEEPGREEN", cv2.COLORMAP_DEEPGREEN),
]

# 1×256 grayscale ramp: index i → gray value i
gray_ramp = np.arange(256, dtype=np.uint8).reshape(1, 256)


def rust_u8_array(values):
    items = ", ".join(str(int(v)) for v in values)
    return f"[\n        {items}\n    ]"


print("// @generated by scripts/gen_colormap_luts.py — do not edit by hand.")
print("// Re-run the script after updating OpenCV to refresh LUT data.")
print()
print("use super::ColormapLut;")
print()

for name, cv2_id in COLORMAPS:
    # cv2.applyColorMap returns BGR — extract RGB channels explicitly
    bgr = cv2.applyColorMap(gray_ramp, cv2_id)[0]  # shape (256, 3), BGR order
    r = bgr[:, 2]  # channel 2 in BGR = R
    g = bgr[:, 1]
    b = bgr[:, 0]  # channel 0 in BGR = B
    print(f"pub static {name}_LUT: ColormapLut = ColormapLut {{")
    print(f"    r: {rust_u8_array(r)},")
    print(f"    g: {rust_u8_array(g)},")
    print(f"    b: {rust_u8_array(b)},")
    print(f"}};")
    print()
