pub mod camera_node;
pub mod compute_node;
pub mod decoder_node;
pub mod foxglove_node;
pub mod logger_node;

use bytes::BufMut;
use foxglove::{Encode, Schema};
use prost::Message;
use ros_z::{MessageTypeInfo, TypeHash, WithTypeInfo};

pub mod protos {
    pub mod camera {
        pub mod v1 {
            include!(concat!(env!("OUT_DIR"), "/bubbaloop.camera.v1.rs"));
        }
    }
    pub mod header {
        pub mod v1 {
            include!(concat!(env!("OUT_DIR"), "/bubbaloop.header.v1.rs"));
        }
    }
    pub mod stats {
        pub mod v1 {
            include!(concat!(env!("OUT_DIR"), "/bubbaloop.stats.v1.rs"));
        }
    }

    // Re-export commonly used types at protos level
    pub use camera::v1::{CompressedImage, RawImage};
    pub use header::v1::Header;
    pub use stats::v1::ImageStats;
}

// Include the FileDescriptorSet bytes generated by prost-build
pub const DESCRIPTOR: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/descriptor.bin"));

impl MessageTypeInfo for protos::CompressedImage {
    fn type_name() -> &'static str {
        "bubbaloop.camera.v1.CompressedImage"
    }

    fn type_hash() -> TypeHash {
        TypeHash::zero()
    }
}

impl WithTypeInfo for protos::CompressedImage {}

impl MessageTypeInfo for protos::RawImage {
    fn type_name() -> &'static str {
        "bubbaloop.camera.v1.RawImage"
    }

    fn type_hash() -> TypeHash {
        TypeHash::zero()
    }
}

impl WithTypeInfo for protos::RawImage {}

impl MessageTypeInfo for protos::ImageStats {
    fn type_name() -> &'static str {
        "bubbaloop.stats.v1.ImageStats"
    }

    fn type_hash() -> TypeHash {
        TypeHash::zero()
    }
}

impl WithTypeInfo for protos::ImageStats {}

impl MessageTypeInfo for protos::Header {
    fn type_name() -> &'static str {
        "bubbaloop.header.v1.Header"
    }

    fn type_hash() -> TypeHash {
        TypeHash::zero()
    }
}

impl WithTypeInfo for protos::Header {}

// Implement foxglove::Encode for ImageStats to publish with schema
impl Encode for protos::ImageStats {
    type Error = prost::EncodeError;

    fn get_schema() -> Option<Schema> {
        Some(Schema::new(
            "bubbaloop.stats.v1.ImageStats",
            "protobuf",
            DESCRIPTOR,
        ))
    }

    fn get_message_encoding() -> String {
        "protobuf".to_string()
    }

    fn encode(&self, buf: &mut impl BufMut) -> Result<(), Self::Error> {
        self.encode_raw(buf);
        Ok(())
    }
}
