[package]
name = "smol_vlm2_video"
version = "0.1.0"
authors = ["Andrew Shen <andrewshen31@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
argh = { workspace = true }
reqwest = { version = "0.12.15", features = ["blocking"] }
kornia = { workspace = true, features = ["v4l"] }
kornia-image = { workspace = true }
kornia-tensor = { workspace = true }
kornia-vlm = { workspace = true, features = ["gstreamer"] }
ctrlc = { workspace = true }
rerun = { workspace = true }
env_logger = { workspace = true }
gstreamer = "0.23.5"
gstreamer-app = "0.23.5"
gstreamer-video = "0.23.5"

[features]
cuda = ["kornia/cuda"]
