[package]
name = "dora-video-capture"
version = "0.1.0"
edition = "2021"

[dependencies]
dora-node-api = { version = "0.3.10", features = ["tracing"] }
dora-image-utils = { path = "../image-utils" }
eyre = "0.6"
kornia = { version = "0.1.9", features = ["gstreamer"] }
