[package]
name = "kornia-rs"
version = "0.1.6-dev"
edition = "2021"
#version.workspace = true
#edition.workspace = true
#description.workspace = true
#homepage.workspace = true
#repository.workspace = true
#categories.workspace = true
#license-file.workspace = true

[dependencies]
kornia-core = { workspace = true }
kornia-image = { workspace = true }
kornia-imgproc = { workspace = true }
kornia-io = { workspace = true, features = ["gstreamer", "jpegturbo"] }
