[package]
name = "kornia-rs"
authors.workspace = true
description = "Kornia top-level crate"
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
kornia-core.workspace = true
kornia-image.workspace = true
kornia-imgproc.workspace = true
kornia-io = { workspace = true, features = ["gstreamer", "jpegturbo"] }
